spring.application.name=kindlebot

# Properties
spring.api.theNewYorker=https://api.github.com/repositories/769113642/contents/NY/
spring.api.theEconomist=https://api.github.com/repositories/737724859/contents/TE/
spring.api.scientificAmerican=https://api.github.com/repositories/769112147/contents/SA/
spring.api.timeMagazine=https://api.github.com/repositories/769109109/contents/TM/

# Logging
aop.logging.enabled=false
# logging.file.name=logs/app.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.level.org.springframework.web: info

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,httptrace,loggers
#management.endpoints.web.exposure.include=*	#not for prod

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

# Show SQL in logs
spring.jpa.show-sql=false

# Include detailed error info in API responses
server.error.include-message=always
server.error.include-binding-errors=always