spring.firebase.credentialsPath=config/serviceAccountKey.json
spring.firebase.projectId=YOUR_PROJECT_ID
spring.firebase.storageBucket=YOUR_PROJECT_ID.appspot.com
spring.firebase.databaseUrl=https://YOUR_PROJECT_ID-default-rtdb.firebaseio.com
