spring.firebase.credentialsPath=config/serviceAccountKey.json
spring.firebase.projectId=YOUR_PROJECT_ID
spring.firebase.storageBucket=YOUR_PROJECT_ID.appspot.com
spring.firebase.databaseUrl=https://YOUR_PROJECT_ID-default-rtdb.firebaseio.com


firebase.apiKey=YOUR_API_KEY
firebase.authDomain=YOUR_PROJECT_ID.firebaseapp.com
firebase.messagingSenderId=xxxxxxxxxxxx
firebase.appId=1:305012535430:web:6d8b4b04253901a11f2107
firebase.appId=1:xxxxxxxxxxxx:web:yyyyyyyyyyyyyyyyyyyyyy